/**
 * Core — serviços internos do sistema (expansão; não substitui lib/escola).
 */
export * from './health'
export * from './config'
export * from './env'
export * from './featureFlags'
export * from './rateLimit'
export * from './cache'
export * from './retry'
export * from './metrics'
export * from './errorReporter'
export * from './dataSanitizer'
export * from './tokenRefresh'
export * from './tokenBlacklist'
export * from './requestLogger'
export * from './pagination'
export * from './escolaContext'
export * from './dates/dateService'
export * from './notifications/inbox'
export * from './jobs/scheduler'
export * from './jobs/runner'
export * from './jobs/parcelasAtrasadas'
export * from './export/pipeline'
export * from './events/bus'
export * from './i18n/i18n'
export * from './import/pipeline'
export * from './quotas'
export * from './tracing'
export * from './circuitBreaker'
export * from './sortFilter'
export * from './idempotency'
export * from './escolaSettings'
export * from './integrations/health'
export * from './webhooks/dispatcher'
export * from './notifications/dispatcher'
export * from './jobs/boletinsBatch'
export * from './jobs/cacheWarmup'
